name: Ubuntu CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          make install
          make install_conan
          make install_doc
      - name: prepare
        run: |
          make prepare
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On
      - name: coverage
        run: |
          cmake --build build --config Debug --target coverage -j4
      - name: testing
        run: |
          cd build
          cd tests
          ctest -j 4
          bash <(curl -s https://codecov.io/bash)